# Generated by Django 2.2.1 on 2019-05-21 09:32

import apiserver.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiserver_url', models.CharField(max_length=400, unique=True, validators=[apiserver.validators.validate_apiserver_url])),
                ('api_rules', models.TextField(unique=True, validators=[apiserver.validators.validate_api_rules])),
                ('access_level', models.IntegerField(default=99)),
                ('active', models.BooleanField(default=True)),
                ('methods', multiselectfield.db.fields.MultiSelectField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=20, null=True)),
                ('ip_address_limiter', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='URL', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
