# Generated by Django 5.2.2 on 2025-06-05 02:05

import apiserver.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0002_url_expected_successful_responses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='limit_ip',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='httpmethod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='api_rules',
            field=models.TextField(validators=[apiserver.validators.validate_api_rules]),
        ),
        migrations.AlterField(
            model_name='url',
            name='apiserver_url',
            field=models.CharField(max_length=400, validators=[apiserver.validators.validate_apiserver_url]),
        ),
        migrations.AlterField(
            model_name='url',
            name='expected_successful_responses',
            field=models.CharField(max_length=50, validators=[apiserver.validators.validate_http_codes]),
        ),
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='ip_address_limiter',
            field=models.TextField(blank=True, null=True, validators=[apiserver.validators.validate_ip_addresses]),
        ),
    ]
